name: build update

on:
  workflow_call:
    inputs:
      run_id:
        required: true
        type: string

permissions:
  contents: write

jobs:
  Update:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{secrets.GITHUB_TOKEN}}

      - name: Download
        uses: martis99/build-download-action@main
        with:
          run_id: ${{inputs.run_id}}

      - name: Commit
        run: |
          git config --global user.email ""
          git config --global user.name "GitHub Actions"
          git add . && git diff --staged --quiet || git commit -m "build: update"
          git push
