name: build
run-name: build-linux

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - '**.md'

  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - '**.md'

  workflow_dispatch:

jobs:
  Ubuntu-Make:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        configuration: [Debug, Release]
        platform: [x64, x86]

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Generate
        run: ./build-linux

      - name: Build
        run: make CONFIG=${{matrix.configuration}} PLATFORM=${{matrix.platform}}

      - name: Copy
        run: cp ./bin/${{matrix.configuration}}-${{matrix.platform}}/build/build ./bin/${{matrix.configuration}}-${{matrix.platform}}/build/build-linux-${{matrix.platform}}-${{matrix.configuration}}

      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: build-linux-${{matrix.platform}}-${{matrix.configuration}}
          path: ./bin/${{matrix.configuration}}-${{matrix.platform}}/build/build-linux-${{matrix.platform}}-${{matrix.configuration}}

  Notify:
    needs: Ubuntu-Make
    runs-on: ubuntu-latest
    strategy:
      matrix:
        system: [make]

    steps:
      - name: Notify
        uses: actions/github-script@v6
        with:
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'test-linux-${{matrix.system}}.yml',
              ref: 'main',
              inputs: {
                run_id: "${{github.run_id}}"
              }
            });
          github-token: ${{secrets.PAT}}
