name: coverage
run-name: coverage

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - '.github/**'

  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - '.github/**'

  workflow_dispatch:

jobs:
  Coverage:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Generate
        run: ./build-linux

      - name: Build
        run: make build/coverage SHOW=false

      - name: Upload
        uses: codecov/codecov-action@v3
        with:
          files: ./bin/Debug-x64/build/lcov.info
