name: Deploy

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  Linux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Generate solution
      run: ./build-linux

    - name: Build
      run: make CONFIG=Release

    - name: Copy binaries
      run: cp ./bin/Release-x64/build/build ./bin/Release-x64/build/build-linux

    - name: Upload
      uses: actions/upload-artifact@v3
      with:
        name: build-linux
        path: ./bin/Release-x64/build/build-linux

  Windows:
    runs-on: windows-latest
    strategy:
      matrix:
        platform: [x64, x86]

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Generate solution
      run: .\build-win-x64.exe

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.1

    - name: Restore NuGet packages
      run: nuget restore .

    - name: Build
      run: msbuild /m /p:Configuration=Release /p:Platform=${{matrix.platform}} .

    - name: Copy binaries
      run: cp .\bin\Release-${{matrix.platform}}\build\build.exe .\bin\Release-${{matrix.platform}}\build\build-win-${{matrix.platform}}.exe

    - name: Upload
      uses: actions/upload-artifact@v3
      with:
        name: build-win-${{matrix.platform}}
        path: .\bin\Release-${{matrix.platform}}\build\build-win-${{matrix.platform}}.exe
