name: deploy

on:
  workflow_dispatch:

jobs:
  Deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Download Linux
        uses: martis99/build-download-action@main
        with:
          workflow: build-linux

      - name: Download Windows
        uses: martis99/build-download-action@main
        with:
          workflow: build-windows

      - name: Rename
        run: |
          cp build-linux-x64-Release build-linux
          cp build-win-x64-Release.exe build-win-x64.exe
          cp build-win-x86-Release.exe build-win-x86.exe

      - name: Upload Linux
        uses: actions/upload-artifact@v3
        with:
          name: build-linux
          path: build-linux

      - name: Upload Windows x64
        uses: actions/upload-artifact@v3
        with:
          name: build-win-x64
          path: build-win-x64.exe

      - name: Upload Windows x86
        uses: actions/upload-artifact@v3
        with:
          name: build-win-x86
          path: build-win-x86.exe

      - name: Notify
        uses: actions/github-script@v6
        with:
          script: |
            await github.rest.repos.createDispatchEvent({
              owner: 'martis99',
              repo: 'build-broadcast',
              event_type: 'build_update',
              client_payload: {
                run_id: "${{github.run_id}}"
              }
            });
          github-token: ${{secrets.PAT}}
