name: test
run-name: test-windows-msbuild

on:
  workflow_dispatch:
    inputs:
      run_id:
        required: false

jobs:
  Windows-MSBuild:
    runs-on: windows-latest
    strategy:
      matrix:
        configuration: [Debug, Release]
        platform: [x64, x86]

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Download
        uses: martis99/build-download-action@main
        with:
          run_id: ${{github.event.inputs.run_id}}
          workflow: build-windows

      - name: Generate
        run: .\build-win-${{matrix.platform}}-${{matrix.configuration}}.exe -S test_sln -G V

      - name: Setup
        uses: microsoft/setup-msbuild@v1.3

      - name: Build
        run: msbuild /m /p:Configuration=${{matrix.configuration}} /p:Platform=${{matrix.platform}} .\test_sln

      - name: Run
        run: .\test_sln\bin\${{matrix.configuration}}-${{matrix.platform}}\app\app.exe
