name: Test

on:
  push:
    branches: [ "main" ]
    paths-ignore:
    - '.github/**'

  pull_request:
    branches: [ "main" ]
    paths-ignore:
    - '.github/**'

  workflow_dispatch:

permissions:
  contents: read

jobs:
  Ubuntu-Make:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        configuration: [Debug, Release]

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Generate solution
      run: ./build-linux

    - name: Build
      run: make CONFIG=${{matrix.configuration}}

    - name: Test - Generate solution
      run: ./bin/${{matrix.configuration}}-x64/build/build -S test_sln

    - name: Test - Build
      run: make -C test_sln slib app CONFIG=${{matrix.configuration}}

    - name: Test - Run test
      run: ./test_sln/bin/${{matrix.configuration}}-x64/app/app

  Windows-MSBuild:
    runs-on: windows-latest
    strategy:
      matrix:
        configuration: [Debug, Release]
        platform: [x64, x86]

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Generate solution
      run: .\build-win-x64.exe

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.1

    - name: Restore NuGet packages
      run: nuget restore .

    - name: Build
      run: msbuild /m /p:Configuration=${{matrix.configuration}} /p:Platform=${{matrix.platform}} .

    - name: Test - Generate solution
      run: .\bin\${{matrix.configuration}}-${{matrix.platform}}\build\build.exe -S test_sln

    - name: Test - Restore NuGet packages
      run: nuget restore .\test_sln

    - name: Test - Build
      run: msbuild /m /p:Configuration=${{matrix.configuration}} /p:Platform=${{matrix.platform}} .\test_sln

    - name: Test - Run test
      run: .\test_sln\bin\${{matrix.configuration}}-${{matrix.platform}}\app\app.exe
