name: Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  Ubuntu-Make:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        configuration: [Debug, Release]

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Generate solution
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: ./build-linux

    - name: Build
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: make CONFIG=${{matrix.configuration}}

    - name: Test - Generate solution
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: ./bin/${{matrix.configuration}}-x64/build/build -S test_sln

    - name: Test - Build
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: make -C test_sln slib app CONFIG=${{matrix.configuration}}

    - name: Test - Run test
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: ./test_sln/bin/${{matrix.configuration}}-x64/app/app

  Windows-MSBuild:
    runs-on: windows-latest
    strategy:
      matrix:
        configuration: [Debug, Release]
        platform: [x64, x86]

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Generate solution
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: .\build-win-x64.exe

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.1

    - name: Restore NuGet packages
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: nuget restore .

    - name: Build
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: msbuild /m /p:Configuration=${{matrix.configuration}} /p:Platform=${{matrix.platform}} .

    - name: Test - Generate solution
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: .\bin\${{matrix.configuration}}-${{matrix.platform}}\build\build.exe -S test_sln

    - name: Test - Restore NuGet packages
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: nuget restore .\test_sln

    - name: Test - Build
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: msbuild /m /p:Configuration=${{matrix.configuration}} /p:Platform=${{matrix.platform}} .\test_sln

    - name: Test - Run test
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: .\test_sln\bin\${{matrix.configuration}}-${{matrix.platform}}\app\app.exe
