name: test
run-name: test-linux-cmake

on:
  workflow_dispatch:
    inputs:
      run_id:
        required: false

jobs:
  Linux-CMake-Make:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        configuration: [Debug, Release]
        platform: [x64, x86]

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Download
        uses: martis99/build-download-action@main
        with:
          run_id: ${{github.event.inputs.run_id}}
          workflow: build-linux

      - name: Generate
        run: ./build-linux-${{matrix.platform}}-${{matrix.configuration}} -S test_sln -G C

      - name: Run CMake
        run: cmake -S test_sln -B test_sln/bin -G "Unix Makefiles"

      - name: Build
        run: make -C test_sln/bin slib app

      - name: Run
        run: ./test_sln/bin/app/app
