#include "t_mk.h"

#include "gen/mk/mk_sln.h"

#include "common.h"
#include "test.h"

TEST(c_small)
{
	START;

	test_gen_file_t out[] = {
		{
			.path = "tmp/Makefile",
			.data = "SLNDIR=$(CURDIR)\n"
				"\n"
				"CONFIGS = Debug\n"
				"CONFIG = Debug\n"
				"\n"
				"SHOW = true\n"
				"\n"
				".PHONY: all check clean\n"
				"\n"
				"all: test\n"
				"\n"
				"check:\n"
				"ifeq ($(filter $(CONFIG),$(CONFIGS)),)\n"
				"	$(error Config '$(CONFIG)' not found. Configs: $(CONFIGS))\n"
				"endif\n"
				"\n"
				".PHONY: test\n"
				"test: check\n"
				"	@$(MAKE) -C test SLNDIR=$(SLNDIR) CONFIG=$(CONFIG)\n"
				"\n"
				".PHONY: test/clean\n"
				"test/clean: check\n"
				"	@$(MAKE) -C test clean SLNDIR=$(SLNDIR) CONFIG=$(CONFIG)\n"
				"\n"
				".PHONY: test/compile\n"
				"test/compile: check\n"
				"	@$(MAKE) -C test compile SLNDIR=$(SLNDIR) CONFIG=$(CONFIG)\n"
				"\n"
				".PHONY: test/coverage\n"
				"test/coverage: check\n"
				"	@$(MAKE) -C test coverage SLNDIR=$(SLNDIR) CONFIG=$(CONFIG)\n"
				"\n"
				"clean: check\n"
				"	@$(MAKE) -C test clean SLNDIR=$(SLNDIR) CONFIG=$(CONFIG)\n",
		},
		{
			.path = "tmp/test/Makefile",
			.data = "OUTDIR = $(SLNDIR)/bin/$(CONFIG)-x64/test/\n"
				"INTDIR = $(SLNDIR)/bin/$(CONFIG)-x64/test/int/\n"
				"REPDIR = $(OUTDIR)coverage-report/\n"
				"DEPS = $(shell find src -name '*.h')\n"
				"SRC_C = $(shell find src -name '*.c')\n"
				"OBJ_C = $(patsubst %.c, $(INTDIR)%.o, $(SRC_C))\n"
				"LCOV = $(OUTDIR)lcov.info\n"
				"COV = $(patsubst %.c, $(INTDIR)%.gcno, $(SRC_C))\n"
				"COV += $(patsubst %.c, $(INTDIR)%.gcda, $(SRC_C))\n"
				"COV += $(LCOV) $(REPDIR)\n"
				"TARGET = $(OUTDIR)test\n"
				"\n"
				"FLAGS = -Isrc\n"
				"CFLAGS += $(FLAGS)\n"
				"LDFLAGS +=\n"
				"\n"
				"RM += -r\n"
				"\n"
				"CONFIG_FLAGS =\n"
				"\n"
				"SHOW = true\n"
				"\n"
				".PHONY: all check check_coverage test compile coverage clean\n"
				"\n"
				"all: test\n"
				"\n"
				"check:\n"
				"ifeq ($(CONFIG), Debug)\n"
				"	$(eval CONFIG_FLAGS += -ggdb3 -O0)\n"
				"endif\n"
				"\n"
				"check_coverage: check\n"
				"	$(eval CONFIG_FLAGS += --coverage -fprofile-abs-path)\n"
				"ifeq (, $(shell which lcov))\n"
				"	$(error \"lcov not found\")\n"
				"endif\n"
				"\n"
				"test: clean compile\n"
				"\n"
				"compile: check $(TARGET)\n"
				"\n"
				"coverage: clean check_coverage $(TARGET)\n"
				"	@$(TARGET) $(ARGS)\n"
				"	@lcov -q -c -d $(SLNDIR) -o $(LCOV)\n"
				"ifeq ($(SHOW), true)\n"
				"	@genhtml -q $(LCOV) -o $(REPDIR)\n"
				"	@open $(REPDIR)index.html\n"
				"endif\n"
				"\n"
				"$(TARGET): $(OBJ_C)\n"
				"	@mkdir -p $(@D)\n"
				"	@$(CC) $(CONFIG_FLAGS) -o $@ $^ $(LDFLAGS)\n"
				"\n"
				"$(INTDIR)%.o: %.c\n"
				"	@mkdir -p $(@D)\n"
				"	@$(CC) $(CONFIG_FLAGS) $(CFLAGS) -c -o $@ $<\n"
				"\n"
				"clean:\n"
				"	@$(RM) $(TARGET) $(OBJ_C) $(COV)\n",

		},
	};

	EXPECT_EQ(test_gen(mk_sln_gen, c_small_in, sizeof(c_small_in), out, sizeof(out)), 0);

	END;
}

TEST(cpp_small)
{
	START;

	test_gen_file_t out[] = {
		{
			.path = "tmp/Makefile",
			.data = "SLNDIR=$(CURDIR)\n"
				"\n"
				"CONFIGS = Debug\n"
				"CONFIG = Debug\n"
				"\n"
				"SHOW = true\n"
				"\n"
				".PHONY: all check clean\n"
				"\n"
				"all: test\n"
				"\n"
				"check:\n"
				"ifeq ($(filter $(CONFIG),$(CONFIGS)),)\n"
				"	$(error Config '$(CONFIG)' not found. Configs: $(CONFIGS))\n"
				"endif\n"
				"\n"
				".PHONY: test\n"
				"test: check\n"
				"	@$(MAKE) -C test SLNDIR=$(SLNDIR) CONFIG=$(CONFIG)\n"
				"\n"
				".PHONY: test/clean\n"
				"test/clean: check\n"
				"	@$(MAKE) -C test clean SLNDIR=$(SLNDIR) CONFIG=$(CONFIG)\n"
				"\n"
				".PHONY: test/compile\n"
				"test/compile: check\n"
				"	@$(MAKE) -C test compile SLNDIR=$(SLNDIR) CONFIG=$(CONFIG)\n"
				"\n"
				".PHONY: test/coverage\n"
				"test/coverage: check\n"
				"	@$(MAKE) -C test coverage SLNDIR=$(SLNDIR) CONFIG=$(CONFIG)\n"
				"\n"
				"clean: check\n"
				"	@$(MAKE) -C test clean SLNDIR=$(SLNDIR) CONFIG=$(CONFIG)\n",
		},
		{
			.path = "tmp/test/Makefile",
			.data = "OUTDIR = $(SLNDIR)/bin/$(CONFIG)-x64/test/\n"
				"INTDIR = $(SLNDIR)/bin/$(CONFIG)-x64/test/int/\n"
				"REPDIR = $(OUTDIR)coverage-report/\n"
				"DEPS = $(shell find src -name '*.h')\n"
				"DEPS += $(shell find src -name '*.hpp')\n"
				"SRC_CPP = $(shell find src -name '*.cpp')\n"
				"OBJ_CPP = $(patsubst %.cpp, $(INTDIR)%.o, $(SRC_CPP))\n"
				"LCOV = $(OUTDIR)lcov.info\n"
				"COV = $(patsubst %.cpp, $(INTDIR)%.gcno, $(SRC_CPP))\n"
				"COV += $(patsubst %.cpp, $(INTDIR)%.gcda, $(SRC_CPP))\n"
				"COV += $(LCOV) $(REPDIR)\n"
				"TARGET = $(OUTDIR)test\n"
				"\n"
				"FLAGS = -Isrc\n"
				"CXXFLAGS += $(FLAGS)\n"
				"LDFLAGS += -lstdc++\n"
				"\n"
				"RM += -r\n"
				"\n"
				"CONFIG_FLAGS =\n"
				"\n"
				"SHOW = true\n"
				"\n"
				".PHONY: all check check_coverage test compile coverage clean\n"
				"\n"
				"all: test\n"
				"\n"
				"check:\n"
				"ifeq ($(CONFIG), Debug)\n"
				"	$(eval CONFIG_FLAGS += -ggdb3 -O0)\n"
				"endif\n"
				"\n"
				"check_coverage: check\n"
				"	$(eval CONFIG_FLAGS += --coverage -fprofile-abs-path)\n"
				"ifeq (, $(shell which lcov))\n"
				"	$(error \"lcov not found\")\n"
				"endif\n"
				"\n"
				"test: clean compile\n"
				"\n"
				"compile: check $(TARGET)\n"
				"\n"
				"coverage: clean check_coverage $(TARGET)\n"
				"	@$(TARGET) $(ARGS)\n"
				"	@lcov -q -c -d $(SLNDIR) -o $(LCOV)\n"
				"ifeq ($(SHOW), true)\n"
				"	@genhtml -q $(LCOV) -o $(REPDIR)\n"
				"	@open $(REPDIR)index.html\n"
				"endif\n"
				"\n"
				"$(TARGET): $(OBJ_CPP)\n"
				"	@mkdir -p $(@D)\n"
				"	@$(CC) $(CONFIG_FLAGS) -o $@ $^ $(LDFLAGS)\n"
				"\n"
				"$(INTDIR)%.o: %.cpp\n"
				"	@mkdir -p $(@D)\n"
				"	@$(CC) $(CONFIG_FLAGS) $(CXXFLAGS) -c -o $@ $<\n"
				"\n"
				"clean:\n"
				"	@$(RM) $(TARGET) $(OBJ_CPP) $(COV)\n",

		},
	};

	EXPECT_EQ(test_gen(mk_sln_gen, cpp_small_in, sizeof(cpp_small_in), out, sizeof(out)), 0);

	END;
}

TEST(c_depends)
{
	START;

	test_gen_file_t out[] = {
		{
			.path = "tmp/Makefile",
			.data = "SLNDIR=$(CURDIR)\n"
				"\n"
				"CONFIGS = Debug\n"
				"CONFIG = Debug\n"
				"\n"
				"SHOW = true\n"
				"\n"
				".PHONY: all check clean\n"
				"\n"
				"all: libtest test\n"
				"\n"
				"check:\n"
				"ifeq ($(filter $(CONFIG),$(CONFIGS)),)\n"
				"	$(error Config '$(CONFIG)' not found. Configs: $(CONFIGS))\n"
				"endif\n"
				"\n"
				".PHONY: libtest\n"
				"libtest: check\n"
				"	@$(MAKE) -C libtest SLNDIR=$(SLNDIR) CONFIG=$(CONFIG)\n"
				"\n"
				".PHONY: libtest/clean\n"
				"libtest/clean: check\n"
				"	@$(MAKE) -C libtest clean SLNDIR=$(SLNDIR) CONFIG=$(CONFIG)\n"
				"\n"
				".PHONY: libtest/compile\n"
				"libtest/compile: check\n"
				"	@$(MAKE) -C libtest compile SLNDIR=$(SLNDIR) CONFIG=$(CONFIG)\n"
				"\n"
				".PHONY: libtest/coverage\n"
				"libtest/coverage: check\n"
				"	@$(MAKE) -C libtest coverage SLNDIR=$(SLNDIR) CONFIG=$(CONFIG)\n"
				"\n"
				".PHONY: test\n"
				"test: check libtest\n"
				"	@$(MAKE) -C test SLNDIR=$(SLNDIR) CONFIG=$(CONFIG)\n"
				"\n"
				".PHONY: test/clean\n"
				"test/clean: check libtest/clean\n"
				"	@$(MAKE) -C test clean SLNDIR=$(SLNDIR) CONFIG=$(CONFIG)\n"
				"\n"
				".PHONY: test/compile\n"
				"test/compile: check libtest/compile\n"
				"	@$(MAKE) -C test compile SLNDIR=$(SLNDIR) CONFIG=$(CONFIG)\n"
				"\n"
				".PHONY: test/coverage\n"
				"test/coverage: check libtest/coverage\n"
				"	@$(MAKE) -C test coverage SLNDIR=$(SLNDIR) CONFIG=$(CONFIG)\n"
				"\n"
				"clean: check\n"
				"	@$(MAKE) -C libtest clean SLNDIR=$(SLNDIR) CONFIG=$(CONFIG)\n"
				"	@$(MAKE) -C test clean SLNDIR=$(SLNDIR) CONFIG=$(CONFIG)\n",
		},
		{
			.path = "tmp/libtest/Makefile",
			.data = "OUTDIR = $(SLNDIR)/bin/$(CONFIG)-x64/libtest/\n"
				"INTDIR = $(SLNDIR)/bin/$(CONFIG)-x64/libtest/int/\n"
				"REPDIR = $(OUTDIR)coverage-report/\n"
				"DEPS = $(shell find src -name '*.h')\n"
				"SRC_C = $(shell find src -name '*.c')\n"
				"OBJ_C = $(patsubst %.c, $(INTDIR)%.o, $(SRC_C))\n"
				"LCOV = $(OUTDIR)lcov.info\n"
				"COV = $(patsubst %.c, $(INTDIR)%.gcno, $(SRC_C))\n"
				"COV += $(patsubst %.c, $(INTDIR)%.gcda, $(SRC_C))\n"
				"COV += $(LCOV) $(REPDIR)\n"
				"TARGET = $(OUTDIR)libtest.a\n"
				"\n"
				"FLAGS = -Isrc\n"
				"CFLAGS += $(FLAGS)\n"
				"\n"
				"RM += -r\n"
				"\n"
				"CONFIG_FLAGS =\n"
				"\n"
				".PHONY: all check check_coverage libtest compile coverage clean\n"
				"\n"
				"all: libtest\n"
				"\n"
				"check:\n"
				"ifeq ($(CONFIG), Debug)\n"
				"	$(eval CONFIG_FLAGS += -ggdb3 -O0)\n"
				"endif\n"
				"\n"
				"check_coverage: check\n"
				"	$(eval CONFIG_FLAGS += --coverage -fprofile-abs-path)\n"
				"ifeq (, $(shell which lcov))\n"
				"	$(error \"lcov not found\")\n"
				"endif\n"
				"\n"
				"libtest: clean compile\n"
				"\n"
				"compile: check $(TARGET)\n"
				"\n"
				"coverage: clean check_coverage $(TARGET)\n"
				"\n"
				"$(TARGET): $(OBJ_C)\n"
				"	@mkdir -p $(@D)\n"
				"	@ar rcs $@ $^\n"
				"\n"
				"$(INTDIR)%.o: %.c\n"
				"	@mkdir -p $(@D)\n"
				"	@$(CC) $(CONFIG_FLAGS) $(CFLAGS) -c -o $@ $<\n"
				"\n"
				"clean:\n"
				"	@$(RM) $(TARGET) $(OBJ_C) $(COV)\n",
		},
		{
			.path = "tmp/test/Makefile",
			.data = "OUTDIR = $(SLNDIR)/bin/$(CONFIG)-x64/test/\n"
				"INTDIR = $(SLNDIR)/bin/$(CONFIG)-x64/test/int/\n"
				"REPDIR = $(OUTDIR)coverage-report/\n"
				"DEPS = $(shell find src -name '*.h')\n"
				"SRC_C = $(shell find src -name '*.c')\n"
				"OBJ_C = $(patsubst %.c, $(INTDIR)%.o, $(SRC_C))\n"
				"LCOV = $(OUTDIR)lcov.info\n"
				"COV = $(patsubst %.c, $(INTDIR)%.gcno, $(SRC_C))\n"
				"COV += $(patsubst %.c, $(INTDIR)%.gcda, $(SRC_C))\n"
				"COV += $(LCOV) $(REPDIR)\n"
				"TARGET = $(OUTDIR)test\n"
				"\n"
				"FLAGS = -Isrc\n"
				"CFLAGS += $(FLAGS)\n"
				"LDFLAGS += -L$(SLNDIR)/bin/$(CONFIG)-x64/libtest/ -l:libtest.a\n"
				"\n"
				"RM += -r\n"
				"\n"
				"CONFIG_FLAGS =\n"
				"\n"
				"SHOW = true\n"
				"\n"
				".PHONY: all check check_coverage test compile coverage clean\n"
				"\n"
				"all: test\n"
				"\n"
				"check:\n"
				"ifeq ($(CONFIG), Debug)\n"
				"	$(eval CONFIG_FLAGS += -ggdb3 -O0)\n"
				"endif\n"
				"\n"
				"check_coverage: check\n"
				"	$(eval CONFIG_FLAGS += --coverage -fprofile-abs-path)\n"
				"ifeq (, $(shell which lcov))\n"
				"	$(error \"lcov not found\")\n"
				"endif\n"
				"\n"
				"test: clean compile\n"
				"\n"
				"compile: check $(TARGET)\n"
				"\n"
				"coverage: clean check_coverage $(TARGET)\n"
				"	@$(TARGET) $(ARGS)\n"
				"	@lcov -q -c -d $(SLNDIR) -o $(LCOV)\n"
				"ifeq ($(SHOW), true)\n"
				"	@genhtml -q $(LCOV) -o $(REPDIR)\n"
				"	@open $(REPDIR)index.html\n"
				"endif\n"
				"\n"
				"$(TARGET): $(OBJ_C)\n"
				"	@mkdir -p $(@D)\n"
				"	@$(CC) $(CONFIG_FLAGS) -o $@ $^ $(LDFLAGS)\n"
				"\n"
				"$(INTDIR)%.o: %.c\n"
				"	@mkdir -p $(@D)\n"
				"	@$(CC) $(CONFIG_FLAGS) $(CFLAGS) -c -o $@ $<\n"
				"\n"
				"clean:\n"
				"	@$(RM) $(TARGET) $(OBJ_C) $(COV)\n",

		},
	};

	EXPECT_EQ(test_gen(mk_sln_gen, c_depends_in, sizeof(c_depends_in), out, sizeof(out)), 0);

	END;
}

STEST(mk)
{
	SSTART;
	RUN(c_small);
	RUN(cpp_small);
	RUN(c_depends);
	SEND;
}
