#include "t_vc.h"

#include "gen/vc/vc_sln.h"

#include "common.h"
#include "mk_vc.h"
#include "test.h"

static const char *PROJ_C = "OUTDIR := $(SLNDIR)/bin/$(CONFIG)-$(PLATFORM)/test/\n"
			    "INTDIR := $(SLNDIR)/bin/$(CONFIG)-$(PLATFORM)/test/int/\n"
			    "REPDIR := $(OUTDIR)coverage-report/\n"
			    "DEPS := $(shell find src -name '*.h')\n"
			    "SRC_C := $(shell find src -name '*.c')\n"
			    "OBJ_C := $(patsubst %.c, $(INTDIR)%.o, $(SRC_C))\n"
			    "LCOV := $(OUTDIR)lcov.info\n"
			    "COV := $(patsubst %.c, $(INTDIR)%.gcno, $(SRC_C))\n"
			    "COV += $(patsubst %.c, $(INTDIR)%.gcda, $(SRC_C))\n"
			    "COV += $(LCOV) $(REPDIR)\n"
			    "TARGET := $(OUTDIR)test\n"
			    "\n"
			    "ifeq ($(PLATFORM), x86_64)\n"
			    "BITS := 64\n"
			    "else\n"
			    "BITS := 32\n"
			    "endif\n"
			    "\n"
			    "FLAGS := -Isrc\n"
			    "CFLAGS += $(FLAGS)\n"
			    "LDFLAGS +=\n"
			    "\n"
			    "RM += -r\n"
			    "\n"
			    "CONFIG_FLAGS :=\n"
			    "\n"
			    "ifeq ($(CONFIG), Debug)\n"
			    "CONFIG_FLAGS += -ggdb3 -O0\n"
			    "endif\n"
			    "\n"
			    "SHOW := true\n"
			    "\n"
			    ".PHONY: all check check_coverage test compile coverage run clean\n"
			    "\n"
			    "all: test\n"
			    "\n"
			    "check:\n"
			    "ifeq (, $(shell which gcc))\n"
			    "\tsudo apt install gcc\n"
			    "endif\n"
			    "\n"
			    "check_coverage: check\n"
			    "\t$(eval CONFIG_FLAGS += --coverage -fprofile-abs-path)\n"
			    "ifeq (, $(shell which lcov))\n"
			    "\tsudo apt install lcov\n"
			    "endif\n"
			    "\n"
			    "test: clean compile\n"
			    "\n"
			    "compile: check $(TARGET)\n"
			    "\n"
			    "coverage: clean check_coverage $(TARGET)\n"
			    "\t@$(TARGET) $(ARGS)\n"
			    "\t@lcov -q -c -d $(SLNDIR) -o $(LCOV)\n"
			    "ifeq ($(SHOW), true)\n"
			    "\t@genhtml -q $(LCOV) -o $(REPDIR)\n"
			    "\t@open $(REPDIR)index.html\n"
			    "endif\n"
			    "\n"
			    "$(TARGET): $(OBJ_C)\n"
			    "\t@mkdir -p $(@D)\n"
			    "\t@$(TCC) $(CONFIG_FLAGS) -o $@ $^ $(LDFLAGS)\n"
			    "\n"
			    "$(INTDIR)%.o: %.c\n"
			    "\t@mkdir -p $(@D)\n"
			    "\t@$(TCC) $(CONFIG_FLAGS) $(CFLAGS) -c -o $@ $<\n"
			    "\n"
			    "run: check $(TARGET)\n"
			    "\n"
			    "clean:\n"
			    "\t@$(RM) $(TARGET) $(OBJ_C) $(COV)\n";

static const char *PROJ_CPP = "OUTDIR := $(SLNDIR)/bin/$(CONFIG)-$(PLATFORM)/test/\n"
			      "INTDIR := $(SLNDIR)/bin/$(CONFIG)-$(PLATFORM)/test/int/\n"
			      "REPDIR := $(OUTDIR)coverage-report/\n"
			      "DEPS := $(shell find src -name '*.h')\n"
			      "DEPS += $(shell find src -name '*.hpp')\n"
			      "SRC_CPP := $(shell find src -name '*.cpp')\n"
			      "OBJ_CPP := $(patsubst %.cpp, $(INTDIR)%.o, $(SRC_CPP))\n"
			      "LCOV := $(OUTDIR)lcov.info\n"
			      "COV := $(patsubst %.cpp, $(INTDIR)%.gcno, $(SRC_CPP))\n"
			      "COV += $(patsubst %.cpp, $(INTDIR)%.gcda, $(SRC_CPP))\n"
			      "COV += $(LCOV) $(REPDIR)\n"
			      "TARGET := $(OUTDIR)test\n"
			      "\n"
			      "ifeq ($(PLATFORM), x86_64)\n"
			      "BITS := 64\n"
			      "else\n"
			      "BITS := 32\n"
			      "endif\n"
			      "\n"
			      "FLAGS := -Isrc\n"
			      "CXXFLAGS += $(FLAGS)\n"
			      "LDFLAGS += -lstdc++\n"
			      "\n"
			      "RM += -r\n"
			      "\n"
			      "CONFIG_FLAGS :=\n"
			      "\n"
			      "ifeq ($(CONFIG), Debug)\n"
			      "CONFIG_FLAGS += -ggdb3 -O0\n"
			      "endif\n"
			      "\n"
			      "SHOW := true\n"
			      "\n"
			      ".PHONY: all check check_coverage test compile coverage run clean\n"
			      "\n"
			      "all: test\n"
			      "\n"
			      "check:\n"
			      "ifeq (, $(shell which gcc))\n"
			      "\tsudo apt install gcc\n"
			      "endif\n"
			      "\n"
			      "check_coverage: check\n"
			      "\t$(eval CONFIG_FLAGS += --coverage -fprofile-abs-path)\n"
			      "ifeq (, $(shell which lcov))\n"
			      "\tsudo apt install lcov\n"
			      "endif\n"
			      "\n"
			      "test: clean compile\n"
			      "\n"
			      "compile: check $(TARGET)\n"
			      "\n"
			      "coverage: clean check_coverage $(TARGET)\n"
			      "\t@$(TARGET) $(ARGS)\n"
			      "\t@lcov -q -c -d $(SLNDIR) -o $(LCOV)\n"
			      "ifeq ($(SHOW), true)\n"
			      "\t@genhtml -q $(LCOV) -o $(REPDIR)\n"
			      "\t@open $(REPDIR)index.html\n"
			      "endif\n"
			      "\n"
			      "$(TARGET): $(OBJ_CPP)\n"
			      "\t@mkdir -p $(@D)\n"
			      "\t@$(TCC) $(CONFIG_FLAGS) -o $@ $^ $(LDFLAGS)\n"
			      "\n"
			      "$(INTDIR)%.o: %.cpp\n"
			      "\t@mkdir -p $(@D)\n"
			      "\t@$(TCC) $(CONFIG_FLAGS) $(CXXFLAGS) -c -o $@ $<\n"
			      "\n"
			      "run: check $(TARGET)\n"
			      "\n"
			      "clean:\n"
			      "\t@$(RM) $(TARGET) $(OBJ_CPP) $(COV)\n";

static const char *TASKS = "{\n"
			   "        \"version\": \"2.0.0\",\n"
			   "        \"tasks\": [\n"
			   "                {\n"
			   "                        \"label\": \"Build-test-Debug-x64\",\n"
			   "                        \"type\": \"shell\",\n"
			   "                        \"command\": \"make\",\n"
			   "                        \"args\": [\n"
			   "                                \"clean\",\n"
			   "                                \"test/compile\",\n"
			   "                                \"CONFIG=Debug\",\n"
			   "                                \"PLATFORM=x64\"\n"
			   "                        ],\n"
			   "                        \"group\": {\n"
			   "                                \"kind\": \"build\",\n"
			   "                                \"isDefault\": true\n"
			   "                        }\n"
			   "                },\n"
			   "                {\n"
			   "                        \"label\": \"Run-test-Debug-x64\",\n"
			   "                        \"type\": \"shell\",\n"
			   "                        \"command\": \"make\",\n"
			   "                        \"args\": [\n"
			   "                                \"clean\",\n"
			   "                                \"test/run\",\n"
			   "                                \"CONFIG=Debug\",\n"
			   "                                \"PLATFORM=x64\"\n"
			   "                        ],\n"
			   "                        \"group\": {\n"
			   "                                \"kind\": \"build\",\n"
			   "                                \"isDefault\": true\n"
			   "                        }\n"
			   "                }\n"
			   "        ]\n"
			   "}";

static const char *LAUNCH = "{\n"
			    "        \"version\": \"0.2.0\",\n"
			    "        \"configurations\": [\n"
			    "                {\n"
			    "                        \"name\": \"test-Debug-x64\",\n"
			    "                        \"type\": \"cppdbg\",\n"
			    "                        \"request\": \"launch\",\n"
			    "                        \"program\": \"${workspaceFolder}/bin/Debug-x64/test/test\",\n"
			    "                        \"args\": [],\n"
			    "                        \"preLaunchTask\": \"Build-test-Debug-x64\",\n"
			    "                        \"stopAtEntry\": false,\n"
			    "                        \"cwd\": \"${workspaceFolder}/test\",\n"
			    "                        \"environment\": [],\n"
			    "                        \"externalConsole\": false,\n"
			    "                        \"MIMode\": \"gdb\",\n"
			    "                        \"setupCommands\": [\n"
			    "                                {\n"
			    "                                        \"description\": \"Enable pretty-printing for gdb\",\n"
			    "                                        \"text\": \"-enable-pretty-printing\",\n"
			    "                                        \"ignoreFailures\": true\n"
			    "                                },\n"
			    "                                {\n"
			    "                                        \"description\": \"Set Disassembly Flavor to Intel\",\n"
			    "                                        \"text\": \"-gdb-set disassembly-flavor intel\",\n"
			    "                                        \"ignoreFailures\": true\n"
			    "                                }\n"
			    "                        ]\n"
			    "                }\n"
			    "        ]\n"
			    "}";

static const char *LAUNCH_ARGS = "{\n"
				 "        \"version\": \"0.2.0\",\n"
				 "        \"configurations\": [\n"
				 "                {\n"
				 "                        \"name\": \"test-Debug-x64\",\n"
				 "                        \"type\": \"cppdbg\",\n"
				 "                        \"request\": \"launch\",\n"
				 "                        \"program\": \"${workspaceFolder}/bin/Debug-x64/test/test\",\n"
				 "                        \"args\": [\n"
				 "                                \"-D\"\n"
				 "                        ],\n"
				 "                        \"preLaunchTask\": \"Build-test-Debug-x64\",\n"
				 "                        \"stopAtEntry\": false,\n"
				 "                        \"cwd\": \"${workspaceFolder}/test\",\n"
				 "                        \"environment\": [],\n"
				 "                        \"externalConsole\": false,\n"
				 "                        \"MIMode\": \"gdb\",\n"
				 "                        \"setupCommands\": [\n"
				 "                                {\n"
				 "                                        \"description\": \"Enable pretty-printing for gdb\",\n"
				 "                                        \"text\": \"-enable-pretty-printing\",\n"
				 "                                        \"ignoreFailures\": true\n"
				 "                                },\n"
				 "                                {\n"
				 "                                        \"description\": \"Set Disassembly Flavor to Intel\",\n"
				 "                                        \"text\": \"-gdb-set disassembly-flavor intel\",\n"
				 "                                        \"ignoreFailures\": true\n"
				 "                                }\n"
				 "                        ]\n"
				 "                }\n"
				 "        ]\n"
				 "}";

static const char *OS_TASKS = "{\n"
			      "        \"version\": \"2.0.0\",\n"
			      "        \"tasks\": [\n"
			      "                {\n"
			      "                        \"label\": \"Build-boot-bin-Debug-x86_64\",\n"
			      "                        \"type\": \"shell\",\n"
			      "                        \"command\": \"make\",\n"
			      "                        \"args\": [\n"
			      "                                \"clean\",\n"
			      "                                \"boot-bin/compile\",\n"
			      "                                \"CONFIG=Debug\",\n"
			      "                                \"PLATFORM=x86_64\"\n"
			      "                        ],\n"
			      "                        \"group\": {\n"
			      "                                \"kind\": \"build\",\n"
			      "                                \"isDefault\": true\n"
			      "                        }\n"
			      "                },\n"
			      "                {\n"
			      "                        \"label\": \"Build-boot-bin-Debug-i386\",\n"
			      "                        \"type\": \"shell\",\n"
			      "                        \"command\": \"make\",\n"
			      "                        \"args\": [\n"
			      "                                \"clean\",\n"
			      "                                \"boot-bin/compile\",\n"
			      "                                \"CONFIG=Debug\",\n"
			      "                                \"PLATFORM=i386\"\n"
			      "                        ],\n"
			      "                        \"group\": {\n"
			      "                                \"kind\": \"build\",\n"
			      "                                \"isDefault\": true\n"
			      "                        }\n"
			      "                },\n"
			      "                {\n"
			      "                        \"label\": \"Build-boot-bin-Release-x86_64\",\n"
			      "                        \"type\": \"shell\",\n"
			      "                        \"command\": \"make\",\n"
			      "                        \"args\": [\n"
			      "                                \"clean\",\n"
			      "                                \"boot-bin/compile\",\n"
			      "                                \"CONFIG=Release\",\n"
			      "                                \"PLATFORM=x86_64\"\n"
			      "                        ],\n"
			      "                        \"group\": {\n"
			      "                                \"kind\": \"build\",\n"
			      "                                \"isDefault\": true\n"
			      "                        }\n"
			      "                },\n"
			      "                {\n"
			      "                        \"label\": \"Build-boot-bin-Release-i386\",\n"
			      "                        \"type\": \"shell\",\n"
			      "                        \"command\": \"make\",\n"
			      "                        \"args\": [\n"
			      "                                \"clean\",\n"
			      "                                \"boot-bin/compile\",\n"
			      "                                \"CONFIG=Release\",\n"
			      "                                \"PLATFORM=i386\"\n"
			      "                        ],\n"
			      "                        \"group\": {\n"
			      "                                \"kind\": \"build\",\n"
			      "                                \"isDefault\": true\n"
			      "                        }\n"
			      "                },\n"
			      "                {\n"
			      "                        \"label\": \"Build-gcc-13.1.0-Debug-x86_64\",\n"
			      "                        \"type\": \"shell\",\n"
			      "                        \"command\": \"make\",\n"
			      "                        \"args\": [\n"
			      "                                \"clean\",\n"
			      "                                \"gcc-13.1.0/compile\",\n"
			      "                                \"CONFIG=Debug\",\n"
			      "                                \"PLATFORM=x86_64\"\n"
			      "                        ],\n"
			      "                        \"group\": {\n"
			      "                                \"kind\": \"build\",\n"
			      "                                \"isDefault\": true\n"
			      "                        }\n"
			      "                },\n"
			      "                {\n"
			      "                        \"label\": \"Build-gcc-13.1.0-Debug-i386\",\n"
			      "                        \"type\": \"shell\",\n"
			      "                        \"command\": \"make\",\n"
			      "                        \"args\": [\n"
			      "                                \"clean\",\n"
			      "                                \"gcc-13.1.0/compile\",\n"
			      "                                \"CONFIG=Debug\",\n"
			      "                                \"PLATFORM=i386\"\n"
			      "                        ],\n"
			      "                        \"group\": {\n"
			      "                                \"kind\": \"build\",\n"
			      "                                \"isDefault\": true\n"
			      "                        }\n"
			      "                },\n"
			      "                {\n"
			      "                        \"label\": \"Build-gcc-13.1.0-Release-x86_64\",\n"
			      "                        \"type\": \"shell\",\n"
			      "                        \"command\": \"make\",\n"
			      "                        \"args\": [\n"
			      "                                \"clean\",\n"
			      "                                \"gcc-13.1.0/compile\",\n"
			      "                                \"CONFIG=Release\",\n"
			      "                                \"PLATFORM=x86_64\"\n"
			      "                        ],\n"
			      "                        \"group\": {\n"
			      "                                \"kind\": \"build\",\n"
			      "                                \"isDefault\": true\n"
			      "                        }\n"
			      "                },\n"
			      "                {\n"
			      "                        \"label\": \"Build-gcc-13.1.0-Release-i386\",\n"
			      "                        \"type\": \"shell\",\n"
			      "                        \"command\": \"make\",\n"
			      "                        \"args\": [\n"
			      "                                \"clean\",\n"
			      "                                \"gcc-13.1.0/compile\",\n"
			      "                                \"CONFIG=Release\",\n"
			      "                                \"PLATFORM=i386\"\n"
			      "                        ],\n"
			      "                        \"group\": {\n"
			      "                                \"kind\": \"build\",\n"
			      "                                \"isDefault\": true\n"
			      "                        }\n"
			      "                },\n"
			      "                {\n"
			      "                        \"label\": \"Build-kernel-bin-Debug-x86_64\",\n"
			      "                        \"type\": \"shell\",\n"
			      "                        \"command\": \"make\",\n"
			      "                        \"args\": [\n"
			      "                                \"clean\",\n"
			      "                                \"kernel-bin/compile\",\n"
			      "                                \"CONFIG=Debug\",\n"
			      "                                \"PLATFORM=x86_64\"\n"
			      "                        ],\n"
			      "                        \"group\": {\n"
			      "                                \"kind\": \"build\",\n"
			      "                                \"isDefault\": true\n"
			      "                        }\n"
			      "                },\n"
			      "                {\n"
			      "                        \"label\": \"Build-kernel-bin-Debug-i386\",\n"
			      "                        \"type\": \"shell\",\n"
			      "                        \"command\": \"make\",\n"
			      "                        \"args\": [\n"
			      "                                \"clean\",\n"
			      "                                \"kernel-bin/compile\",\n"
			      "                                \"CONFIG=Debug\",\n"
			      "                                \"PLATFORM=i386\"\n"
			      "                        ],\n"
			      "                        \"group\": {\n"
			      "                                \"kind\": \"build\",\n"
			      "                                \"isDefault\": true\n"
			      "                        }\n"
			      "                },\n"
			      "                {\n"
			      "                        \"label\": \"Build-kernel-bin-Release-x86_64\",\n"
			      "                        \"type\": \"shell\",\n"
			      "                        \"command\": \"make\",\n"
			      "                        \"args\": [\n"
			      "                                \"clean\",\n"
			      "                                \"kernel-bin/compile\",\n"
			      "                                \"CONFIG=Release\",\n"
			      "                                \"PLATFORM=x86_64\"\n"
			      "                        ],\n"
			      "                        \"group\": {\n"
			      "                                \"kind\": \"build\",\n"
			      "                                \"isDefault\": true\n"
			      "                        }\n"
			      "                },\n"
			      "                {\n"
			      "                        \"label\": \"Build-kernel-bin-Release-i386\",\n"
			      "                        \"type\": \"shell\",\n"
			      "                        \"command\": \"make\",\n"
			      "                        \"args\": [\n"
			      "                                \"clean\",\n"
			      "                                \"kernel-bin/compile\",\n"
			      "                                \"CONFIG=Release\",\n"
			      "                                \"PLATFORM=i386\"\n"
			      "                        ],\n"
			      "                        \"group\": {\n"
			      "                                \"kind\": \"build\",\n"
			      "                                \"isDefault\": true\n"
			      "                        }\n"
			      "                },\n"
			      "                {\n"
			      "                        \"label\": \"Build-kernel-elf-Debug-x86_64\",\n"
			      "                        \"type\": \"shell\",\n"
			      "                        \"command\": \"make\",\n"
			      "                        \"args\": [\n"
			      "                                \"clean\",\n"
			      "                                \"kernel-elf/compile\",\n"
			      "                                \"CONFIG=Debug\",\n"
			      "                                \"PLATFORM=x86_64\"\n"
			      "                        ],\n"
			      "                        \"group\": {\n"
			      "                                \"kind\": \"build\",\n"
			      "                                \"isDefault\": true\n"
			      "                        }\n"
			      "                },\n"
			      "                {\n"
			      "                        \"label\": \"Build-kernel-elf-Debug-i386\",\n"
			      "                        \"type\": \"shell\",\n"
			      "                        \"command\": \"make\",\n"
			      "                        \"args\": [\n"
			      "                                \"clean\",\n"
			      "                                \"kernel-elf/compile\",\n"
			      "                                \"CONFIG=Debug\",\n"
			      "                                \"PLATFORM=i386\"\n"
			      "                        ],\n"
			      "                        \"group\": {\n"
			      "                                \"kind\": \"build\",\n"
			      "                                \"isDefault\": true\n"
			      "                        }\n"
			      "                },\n"
			      "                {\n"
			      "                        \"label\": \"Build-kernel-elf-Release-x86_64\",\n"
			      "                        \"type\": \"shell\",\n"
			      "                        \"command\": \"make\",\n"
			      "                        \"args\": [\n"
			      "                                \"clean\",\n"
			      "                                \"kernel-elf/compile\",\n"
			      "                                \"CONFIG=Release\",\n"
			      "                                \"PLATFORM=x86_64\"\n"
			      "                        ],\n"
			      "                        \"group\": {\n"
			      "                                \"kind\": \"build\",\n"
			      "                                \"isDefault\": true\n"
			      "                        }\n"
			      "                },\n"
			      "                {\n"
			      "                        \"label\": \"Build-kernel-elf-Release-i386\",\n"
			      "                        \"type\": \"shell\",\n"
			      "                        \"command\": \"make\",\n"
			      "                        \"args\": [\n"
			      "                                \"clean\",\n"
			      "                                \"kernel-elf/compile\",\n"
			      "                                \"CONFIG=Release\",\n"
			      "                                \"PLATFORM=i386\"\n"
			      "                        ],\n"
			      "                        \"group\": {\n"
			      "                                \"kind\": \"build\",\n"
			      "                                \"isDefault\": true\n"
			      "                        }\n"
			      "                },\n"
			      "                {\n"
			      "                        \"label\": \"Build-image-disk-Debug-x86_64\",\n"
			      "                        \"type\": \"shell\",\n"
			      "                        \"command\": \"make\",\n"
			      "                        \"args\": [\n"
			      "                                \"clean\",\n"
			      "                                \"image-disk/compile\",\n"
			      "                                \"CONFIG=Debug\",\n"
			      "                                \"PLATFORM=x86_64\"\n"
			      "                        ],\n"
			      "                        \"isBackground\": true,\n"
			      "                        \"problemMatcher\": [\n"
			      "                                {\n"
			      "                                        \"pattern\": [\n"
			      "                                        {\n"
			      "                                                \"regexp\": \".\",\n"
			      "                                                \"file\": 1,\n"
			      "                                                \"location\": 2,\n"
			      "                                                \"message\": 3\n"
			      "                                        }\n"
			      "                                        ],\n"
			      "                                        \"background\": {\n"
			      "                                                \"activeOnStart\": true,\n"
			      "                                                \"beginsPattern\": \".\",\n"
			      "                                                \"endsPattern\": \".\",\n"
			      "                                        }\n"
			      "                                }\n"
			      "                        ],\n"
			      "                        \"group\": {\n"
			      "                                \"kind\": \"build\",\n"
			      "                                \"isDefault\": true\n"
			      "                        }\n"
			      "                },\n"
			      "                {\n"
			      "                        \"label\": \"Build-image-disk-Debug-i386\",\n"
			      "                        \"type\": \"shell\",\n"
			      "                        \"command\": \"make\",\n"
			      "                        \"args\": [\n"
			      "                                \"clean\",\n"
			      "                                \"image-disk/compile\",\n"
			      "                                \"CONFIG=Debug\",\n"
			      "                                \"PLATFORM=i386\"\n"
			      "                        ],\n"
			      "                        \"isBackground\": true,\n"
			      "                        \"problemMatcher\": [\n"
			      "                                {\n"
			      "                                        \"pattern\": [\n"
			      "                                        {\n"
			      "                                                \"regexp\": \".\",\n"
			      "                                                \"file\": 1,\n"
			      "                                                \"location\": 2,\n"
			      "                                                \"message\": 3\n"
			      "                                        }\n"
			      "                                        ],\n"
			      "                                        \"background\": {\n"
			      "                                                \"activeOnStart\": true,\n"
			      "                                                \"beginsPattern\": \".\",\n"
			      "                                                \"endsPattern\": \".\",\n"
			      "                                        }\n"
			      "                                }\n"
			      "                        ],\n"
			      "                        \"group\": {\n"
			      "                                \"kind\": \"build\",\n"
			      "                                \"isDefault\": true\n"
			      "                        }\n"
			      "                },\n"
			      "                {\n"
			      "                        \"label\": \"Build-image-disk-Release-x86_64\",\n"
			      "                        \"type\": \"shell\",\n"
			      "                        \"command\": \"make\",\n"
			      "                        \"args\": [\n"
			      "                                \"clean\",\n"
			      "                                \"image-disk/compile\",\n"
			      "                                \"CONFIG=Release\",\n"
			      "                                \"PLATFORM=x86_64\"\n"
			      "                        ],\n"
			      "                        \"isBackground\": true,\n"
			      "                        \"problemMatcher\": [\n"
			      "                                {\n"
			      "                                        \"pattern\": [\n"
			      "                                        {\n"
			      "                                                \"regexp\": \".\",\n"
			      "                                                \"file\": 1,\n"
			      "                                                \"location\": 2,\n"
			      "                                                \"message\": 3\n"
			      "                                        }\n"
			      "                                        ],\n"
			      "                                        \"background\": {\n"
			      "                                                \"activeOnStart\": true,\n"
			      "                                                \"beginsPattern\": \".\",\n"
			      "                                                \"endsPattern\": \".\",\n"
			      "                                        }\n"
			      "                                }\n"
			      "                        ],\n"
			      "                        \"group\": {\n"
			      "                                \"kind\": \"build\",\n"
			      "                                \"isDefault\": true\n"
			      "                        }\n"
			      "                },\n"
			      "                {\n"
			      "                        \"label\": \"Build-image-disk-Release-i386\",\n"
			      "                        \"type\": \"shell\",\n"
			      "                        \"command\": \"make\",\n"
			      "                        \"args\": [\n"
			      "                                \"clean\",\n"
			      "                                \"image-disk/compile\",\n"
			      "                                \"CONFIG=Release\",\n"
			      "                                \"PLATFORM=i386\"\n"
			      "                        ],\n"
			      "                        \"isBackground\": true,\n"
			      "                        \"problemMatcher\": [\n"
			      "                                {\n"
			      "                                        \"pattern\": [\n"
			      "                                        {\n"
			      "                                                \"regexp\": \".\",\n"
			      "                                                \"file\": 1,\n"
			      "                                                \"location\": 2,\n"
			      "                                                \"message\": 3\n"
			      "                                        }\n"
			      "                                        ],\n"
			      "                                        \"background\": {\n"
			      "                                                \"activeOnStart\": true,\n"
			      "                                                \"beginsPattern\": \".\",\n"
			      "                                                \"endsPattern\": \".\",\n"
			      "                                        }\n"
			      "                                }\n"
			      "                        ],\n"
			      "                        \"group\": {\n"
			      "                                \"kind\": \"build\",\n"
			      "                                \"isDefault\": true\n"
			      "                        }\n"
			      "                },\n"
			      "                {\n"
			      "                        \"label\": \"Run-image-disk-Debug-x86_64\",\n"
			      "                        \"type\": \"shell\",\n"
			      "                        \"command\": \"make\",\n"
			      "                        \"args\": [\n"
			      "                                \"clean\",\n"
			      "                                \"image-disk/run\",\n"
			      "                                \"CONFIG=Debug\",\n"
			      "                                \"PLATFORM=x86_64\"\n"
			      "                        ],\n"
			      "                        \"isBackground\": true,\n"
			      "                        \"problemMatcher\": [\n"
			      "                                {\n"
			      "                                        \"pattern\": [\n"
			      "                                        {\n"
			      "                                                \"regexp\": \".\",\n"
			      "                                                \"file\": 1,\n"
			      "                                                \"location\": 2,\n"
			      "                                                \"message\": 3\n"
			      "                                        }\n"
			      "                                        ],\n"
			      "                                        \"background\": {\n"
			      "                                                \"activeOnStart\": true,\n"
			      "                                                \"beginsPattern\": \".\",\n"
			      "                                                \"endsPattern\": \".\",\n"
			      "                                        }\n"
			      "                                }\n"
			      "                        ],\n"
			      "                        \"group\": {\n"
			      "                                \"kind\": \"build\",\n"
			      "                                \"isDefault\": true\n"
			      "                        }\n"
			      "                },\n"
			      "                {\n"
			      "                        \"label\": \"Run-image-disk-Debug-i386\",\n"
			      "                        \"type\": \"shell\",\n"
			      "                        \"command\": \"make\",\n"
			      "                        \"args\": [\n"
			      "                                \"clean\",\n"
			      "                                \"image-disk/run\",\n"
			      "                                \"CONFIG=Debug\",\n"
			      "                                \"PLATFORM=i386\"\n"
			      "                        ],\n"
			      "                        \"isBackground\": true,\n"
			      "                        \"problemMatcher\": [\n"
			      "                                {\n"
			      "                                        \"pattern\": [\n"
			      "                                        {\n"
			      "                                                \"regexp\": \".\",\n"
			      "                                                \"file\": 1,\n"
			      "                                                \"location\": 2,\n"
			      "                                                \"message\": 3\n"
			      "                                        }\n"
			      "                                        ],\n"
			      "                                        \"background\": {\n"
			      "                                                \"activeOnStart\": true,\n"
			      "                                                \"beginsPattern\": \".\",\n"
			      "                                                \"endsPattern\": \".\",\n"
			      "                                        }\n"
			      "                                }\n"
			      "                        ],\n"
			      "                        \"group\": {\n"
			      "                                \"kind\": \"build\",\n"
			      "                                \"isDefault\": true\n"
			      "                        }\n"
			      "                },\n"
			      "                {\n"
			      "                        \"label\": \"Run-image-disk-Release-x86_64\",\n"
			      "                        \"type\": \"shell\",\n"
			      "                        \"command\": \"make\",\n"
			      "                        \"args\": [\n"
			      "                                \"clean\",\n"
			      "                                \"image-disk/run\",\n"
			      "                                \"CONFIG=Release\",\n"
			      "                                \"PLATFORM=x86_64\"\n"
			      "                        ],\n"
			      "                        \"isBackground\": true,\n"
			      "                        \"problemMatcher\": [\n"
			      "                                {\n"
			      "                                        \"pattern\": [\n"
			      "                                        {\n"
			      "                                                \"regexp\": \".\",\n"
			      "                                                \"file\": 1,\n"
			      "                                                \"location\": 2,\n"
			      "                                                \"message\": 3\n"
			      "                                        }\n"
			      "                                        ],\n"
			      "                                        \"background\": {\n"
			      "                                                \"activeOnStart\": true,\n"
			      "                                                \"beginsPattern\": \".\",\n"
			      "                                                \"endsPattern\": \".\",\n"
			      "                                        }\n"
			      "                                }\n"
			      "                        ],\n"
			      "                        \"group\": {\n"
			      "                                \"kind\": \"build\",\n"
			      "                                \"isDefault\": true\n"
			      "                        }\n"
			      "                },\n"
			      "                {\n"
			      "                        \"label\": \"Run-image-disk-Release-i386\",\n"
			      "                        \"type\": \"shell\",\n"
			      "                        \"command\": \"make\",\n"
			      "                        \"args\": [\n"
			      "                                \"clean\",\n"
			      "                                \"image-disk/run\",\n"
			      "                                \"CONFIG=Release\",\n"
			      "                                \"PLATFORM=i386\"\n"
			      "                        ],\n"
			      "                        \"isBackground\": true,\n"
			      "                        \"problemMatcher\": [\n"
			      "                                {\n"
			      "                                        \"pattern\": [\n"
			      "                                        {\n"
			      "                                                \"regexp\": \".\",\n"
			      "                                                \"file\": 1,\n"
			      "                                                \"location\": 2,\n"
			      "                                                \"message\": 3\n"
			      "                                        }\n"
			      "                                        ],\n"
			      "                                        \"background\": {\n"
			      "                                                \"activeOnStart\": true,\n"
			      "                                                \"beginsPattern\": \".\",\n"
			      "                                                \"endsPattern\": \".\",\n"
			      "                                        }\n"
			      "                                }\n"
			      "                        ],\n"
			      "                        \"group\": {\n"
			      "                                \"kind\": \"build\",\n"
			      "                                \"isDefault\": true\n"
			      "                        }\n"
			      "                },\n"
			      "                {\n"
			      "                        \"label\": \"Build-image-floppy-Debug-x86_64\",\n"
			      "                        \"type\": \"shell\",\n"
			      "                        \"command\": \"make\",\n"
			      "                        \"args\": [\n"
			      "                                \"clean\",\n"
			      "                                \"image-floppy/compile\",\n"
			      "                                \"CONFIG=Debug\",\n"
			      "                                \"PLATFORM=x86_64\"\n"
			      "                        ],\n"
			      "                        \"isBackground\": true,\n"
			      "                        \"problemMatcher\": [\n"
			      "                                {\n"
			      "                                        \"pattern\": [\n"
			      "                                        {\n"
			      "                                                \"regexp\": \".\",\n"
			      "                                                \"file\": 1,\n"
			      "                                                \"location\": 2,\n"
			      "                                                \"message\": 3\n"
			      "                                        }\n"
			      "                                        ],\n"
			      "                                        \"background\": {\n"
			      "                                                \"activeOnStart\": true,\n"
			      "                                                \"beginsPattern\": \".\",\n"
			      "                                                \"endsPattern\": \".\",\n"
			      "                                        }\n"
			      "                                }\n"
			      "                        ],\n"
			      "                        \"group\": {\n"
			      "                                \"kind\": \"build\",\n"
			      "                                \"isDefault\": true\n"
			      "                        }\n"
			      "                },\n"
			      "                {\n"
			      "                        \"label\": \"Build-image-floppy-Debug-i386\",\n"
			      "                        \"type\": \"shell\",\n"
			      "                        \"command\": \"make\",\n"
			      "                        \"args\": [\n"
			      "                                \"clean\",\n"
			      "                                \"image-floppy/compile\",\n"
			      "                                \"CONFIG=Debug\",\n"
			      "                                \"PLATFORM=i386\"\n"
			      "                        ],\n"
			      "                        \"isBackground\": true,\n"
			      "                        \"problemMatcher\": [\n"
			      "                                {\n"
			      "                                        \"pattern\": [\n"
			      "                                        {\n"
			      "                                                \"regexp\": \".\",\n"
			      "                                                \"file\": 1,\n"
			      "                                                \"location\": 2,\n"
			      "                                                \"message\": 3\n"
			      "                                        }\n"
			      "                                        ],\n"
			      "                                        \"background\": {\n"
			      "                                                \"activeOnStart\": true,\n"
			      "                                                \"beginsPattern\": \".\",\n"
			      "                                                \"endsPattern\": \".\",\n"
			      "                                        }\n"
			      "                                }\n"
			      "                        ],\n"
			      "                        \"group\": {\n"
			      "                                \"kind\": \"build\",\n"
			      "                                \"isDefault\": true\n"
			      "                        }\n"
			      "                },\n"
			      "                {\n"
			      "                        \"label\": \"Build-image-floppy-Release-x86_64\",\n"
			      "                        \"type\": \"shell\",\n"
			      "                        \"command\": \"make\",\n"
			      "                        \"args\": [\n"
			      "                                \"clean\",\n"
			      "                                \"image-floppy/compile\",\n"
			      "                                \"CONFIG=Release\",\n"
			      "                                \"PLATFORM=x86_64\"\n"
			      "                        ],\n"
			      "                        \"isBackground\": true,\n"
			      "                        \"problemMatcher\": [\n"
			      "                                {\n"
			      "                                        \"pattern\": [\n"
			      "                                        {\n"
			      "                                                \"regexp\": \".\",\n"
			      "                                                \"file\": 1,\n"
			      "                                                \"location\": 2,\n"
			      "                                                \"message\": 3\n"
			      "                                        }\n"
			      "                                        ],\n"
			      "                                        \"background\": {\n"
			      "                                                \"activeOnStart\": true,\n"
			      "                                                \"beginsPattern\": \".\",\n"
			      "                                                \"endsPattern\": \".\",\n"
			      "                                        }\n"
			      "                                }\n"
			      "                        ],\n"
			      "                        \"group\": {\n"
			      "                                \"kind\": \"build\",\n"
			      "                                \"isDefault\": true\n"
			      "                        }\n"
			      "                },\n"
			      "                {\n"
			      "                        \"label\": \"Build-image-floppy-Release-i386\",\n"
			      "                        \"type\": \"shell\",\n"
			      "                        \"command\": \"make\",\n"
			      "                        \"args\": [\n"
			      "                                \"clean\",\n"
			      "                                \"image-floppy/compile\",\n"
			      "                                \"CONFIG=Release\",\n"
			      "                                \"PLATFORM=i386\"\n"
			      "                        ],\n"
			      "                        \"isBackground\": true,\n"
			      "                        \"problemMatcher\": [\n"
			      "                                {\n"
			      "                                        \"pattern\": [\n"
			      "                                        {\n"
			      "                                                \"regexp\": \".\",\n"
			      "                                                \"file\": 1,\n"
			      "                                                \"location\": 2,\n"
			      "                                                \"message\": 3\n"
			      "                                        }\n"
			      "                                        ],\n"
			      "                                        \"background\": {\n"
			      "                                                \"activeOnStart\": true,\n"
			      "                                                \"beginsPattern\": \".\",\n"
			      "                                                \"endsPattern\": \".\",\n"
			      "                                        }\n"
			      "                                }\n"
			      "                        ],\n"
			      "                        \"group\": {\n"
			      "                                \"kind\": \"build\",\n"
			      "                                \"isDefault\": true\n"
			      "                        }\n"
			      "                },\n"
			      "                {\n"
			      "                        \"label\": \"Run-image-floppy-Debug-x86_64\",\n"
			      "                        \"type\": \"shell\",\n"
			      "                        \"command\": \"make\",\n"
			      "                        \"args\": [\n"
			      "                                \"clean\",\n"
			      "                                \"image-floppy/run\",\n"
			      "                                \"CONFIG=Debug\",\n"
			      "                                \"PLATFORM=x86_64\"\n"
			      "                        ],\n"
			      "                        \"isBackground\": true,\n"
			      "                        \"problemMatcher\": [\n"
			      "                                {\n"
			      "                                        \"pattern\": [\n"
			      "                                        {\n"
			      "                                                \"regexp\": \".\",\n"
			      "                                                \"file\": 1,\n"
			      "                                                \"location\": 2,\n"
			      "                                                \"message\": 3\n"
			      "                                        }\n"
			      "                                        ],\n"
			      "                                        \"background\": {\n"
			      "                                                \"activeOnStart\": true,\n"
			      "                                                \"beginsPattern\": \".\",\n"
			      "                                                \"endsPattern\": \".\",\n"
			      "                                        }\n"
			      "                                }\n"
			      "                        ],\n"
			      "                        \"group\": {\n"
			      "                                \"kind\": \"build\",\n"
			      "                                \"isDefault\": true\n"
			      "                        }\n"
			      "                },\n"
			      "                {\n"
			      "                        \"label\": \"Run-image-floppy-Debug-i386\",\n"
			      "                        \"type\": \"shell\",\n"
			      "                        \"command\": \"make\",\n"
			      "                        \"args\": [\n"
			      "                                \"clean\",\n"
			      "                                \"image-floppy/run\",\n"
			      "                                \"CONFIG=Debug\",\n"
			      "                                \"PLATFORM=i386\"\n"
			      "                        ],\n"
			      "                        \"isBackground\": true,\n"
			      "                        \"problemMatcher\": [\n"
			      "                                {\n"
			      "                                        \"pattern\": [\n"
			      "                                        {\n"
			      "                                                \"regexp\": \".\",\n"
			      "                                                \"file\": 1,\n"
			      "                                                \"location\": 2,\n"
			      "                                                \"message\": 3\n"
			      "                                        }\n"
			      "                                        ],\n"
			      "                                        \"background\": {\n"
			      "                                                \"activeOnStart\": true,\n"
			      "                                                \"beginsPattern\": \".\",\n"
			      "                                                \"endsPattern\": \".\",\n"
			      "                                        }\n"
			      "                                }\n"
			      "                        ],\n"
			      "                        \"group\": {\n"
			      "                                \"kind\": \"build\",\n"
			      "                                \"isDefault\": true\n"
			      "                        }\n"
			      "                },\n"
			      "                {\n"
			      "                        \"label\": \"Run-image-floppy-Release-x86_64\",\n"
			      "                        \"type\": \"shell\",\n"
			      "                        \"command\": \"make\",\n"
			      "                        \"args\": [\n"
			      "                                \"clean\",\n"
			      "                                \"image-floppy/run\",\n"
			      "                                \"CONFIG=Release\",\n"
			      "                                \"PLATFORM=x86_64\"\n"
			      "                        ],\n"
			      "                        \"isBackground\": true,\n"
			      "                        \"problemMatcher\": [\n"
			      "                                {\n"
			      "                                        \"pattern\": [\n"
			      "                                        {\n"
			      "                                                \"regexp\": \".\",\n"
			      "                                                \"file\": 1,\n"
			      "                                                \"location\": 2,\n"
			      "                                                \"message\": 3\n"
			      "                                        }\n"
			      "                                        ],\n"
			      "                                        \"background\": {\n"
			      "                                                \"activeOnStart\": true,\n"
			      "                                                \"beginsPattern\": \".\",\n"
			      "                                                \"endsPattern\": \".\",\n"
			      "                                        }\n"
			      "                                }\n"
			      "                        ],\n"
			      "                        \"group\": {\n"
			      "                                \"kind\": \"build\",\n"
			      "                                \"isDefault\": true\n"
			      "                        }\n"
			      "                },\n"
			      "                {\n"
			      "                        \"label\": \"Run-image-floppy-Release-i386\",\n"
			      "                        \"type\": \"shell\",\n"
			      "                        \"command\": \"make\",\n"
			      "                        \"args\": [\n"
			      "                                \"clean\",\n"
			      "                                \"image-floppy/run\",\n"
			      "                                \"CONFIG=Release\",\n"
			      "                                \"PLATFORM=i386\"\n"
			      "                        ],\n"
			      "                        \"isBackground\": true,\n"
			      "                        \"problemMatcher\": [\n"
			      "                                {\n"
			      "                                        \"pattern\": [\n"
			      "                                        {\n"
			      "                                                \"regexp\": \".\",\n"
			      "                                                \"file\": 1,\n"
			      "                                                \"location\": 2,\n"
			      "                                                \"message\": 3\n"
			      "                                        }\n"
			      "                                        ],\n"
			      "                                        \"background\": {\n"
			      "                                                \"activeOnStart\": true,\n"
			      "                                                \"beginsPattern\": \".\",\n"
			      "                                                \"endsPattern\": \".\",\n"
			      "                                        }\n"
			      "                                }\n"
			      "                        ],\n"
			      "                        \"group\": {\n"
			      "                                \"kind\": \"build\",\n"
			      "                                \"isDefault\": true\n"
			      "                        }\n"
			      "                }\n"
			      "        ]\n"
			      "}\n";

static const char *OS_LAUNCH = "{\n"
			       "        \"version\": \"0.2.0\",\n"
			       "        \"configurations\": [\n"
			       "                {\n"
			       "                        \"name\": \"image-disk-Debug-x86_64\",\n"
			       "                        \"type\": \"cppdbg\",\n"
			       "                        \"request\": \"launch\",\n"
			       "                        \"program\": \"${workspaceFolder}/bin/Debug-x86_64/os/kernel/elf/kernel.elf\",\n"
			       "                        \"args\": [],\n"
			       "                        \"miDebuggerServerAddress\": \"localhost:1234\",\n"
			       "                        \"preLaunchTask\": \"Run-image-disk-Debug-x86_64\",\n"
			       "                        \"stopAtEntry\": false,\n"
			       "                        \"cwd\": \"${workspaceFolder}/os/image/disk\",\n"
			       "                        \"environment\": [],\n"
			       "                        \"externalConsole\": false,\n"
			       "                        \"MIMode\": \"gdb\",\n"
			       "                        \"setupCommands\": [\n"
			       "                                {\n"
			       "                                        \"description\": \"Enable pretty-printing for gdb\",\n"
			       "                                        \"text\": \"-enable-pretty-printing\",\n"
			       "                                        \"ignoreFailures\": true\n"
			       "                                },\n"
			       "                                {\n"
			       "                                        \"description\": \"Set Disassembly Flavor to Intel\",\n"
			       "                                        \"text\": \"-gdb-set disassembly-flavor intel\",\n"
			       "                                        \"ignoreFailures\": true\n"
			       "                                }\n"
			       "                        ]\n"
			       "                },\n"
			       "                {\n"
			       "                        \"name\": \"image-disk-Debug-i386\",\n"
			       "                        \"type\": \"cppdbg\",\n"
			       "                        \"request\": \"launch\",\n"
			       "                        \"program\": \"${workspaceFolder}/bin/Debug-i386/os/kernel/elf/kernel.elf\",\n"
			       "                        \"args\": [],\n"
			       "                        \"miDebuggerServerAddress\": \"localhost:1234\",\n"
			       "                        \"preLaunchTask\": \"Run-image-disk-Debug-i386\",\n"
			       "                        \"stopAtEntry\": false,\n"
			       "                        \"cwd\": \"${workspaceFolder}/os/image/disk\",\n"
			       "                        \"environment\": [],\n"
			       "                        \"externalConsole\": false,\n"
			       "                        \"MIMode\": \"gdb\",\n"
			       "                        \"setupCommands\": [\n"
			       "                                {\n"
			       "                                        \"description\": \"Enable pretty-printing for gdb\",\n"
			       "                                        \"text\": \"-enable-pretty-printing\",\n"
			       "                                        \"ignoreFailures\": true\n"
			       "                                },\n"
			       "                                {\n"
			       "                                        \"description\": \"Set Disassembly Flavor to Intel\",\n"
			       "                                        \"text\": \"-gdb-set disassembly-flavor intel\",\n"
			       "                                        \"ignoreFailures\": true\n"
			       "                                }\n"
			       "                        ]\n"
			       "                },\n"
			       "                {\n"
			       "                        \"name\": \"image-disk-Release-x86_64\",\n"
			       "                        \"type\": \"f5anything\",\n"
			       "                        \"request\": \"launch\",\n"
			       "                        \"preLaunchTask\": \"Run-image-disk-Release-x86_64\",\n"
			       "                },\n"
			       "                {\n"
			       "                        \"name\": \"image-disk-Release-i386\",\n"
			       "                        \"type\": \"f5anything\",\n"
			       "                        \"request\": \"launch\",\n"
			       "                        \"preLaunchTask\": \"Run-image-disk-Release-i386\",\n"
			       "                },\n"
			       "                {\n"
			       "                        \"name\": \"image-floppy-Debug-x86_64\",\n"
			       "                        \"type\": \"cppdbg\",\n"
			       "                        \"request\": \"launch\",\n"
			       "                        \"program\": \"${workspaceFolder}/bin/Debug-x86_64/os/kernel/elf/kernel.elf\",\n"
			       "                        \"args\": [],\n"
			       "                        \"miDebuggerServerAddress\": \"localhost:1234\",\n"
			       "                        \"preLaunchTask\": \"Run-image-floppy-Debug-x86_64\",\n"
			       "                        \"stopAtEntry\": false,\n"
			       "                        \"cwd\": \"${workspaceFolder}/os/image/floppy\",\n"
			       "                        \"environment\": [],\n"
			       "                        \"externalConsole\": false,\n"
			       "                        \"MIMode\": \"gdb\",\n"
			       "                        \"setupCommands\": [\n"
			       "                                {\n"
			       "                                        \"description\": \"Enable pretty-printing for gdb\",\n"
			       "                                        \"text\": \"-enable-pretty-printing\",\n"
			       "                                        \"ignoreFailures\": true\n"
			       "                                },\n"
			       "                                {\n"
			       "                                        \"description\": \"Set Disassembly Flavor to Intel\",\n"
			       "                                        \"text\": \"-gdb-set disassembly-flavor intel\",\n"
			       "                                        \"ignoreFailures\": true\n"
			       "                                }\n"
			       "                        ]\n"
			       "                },\n"
			       "                {\n"
			       "                        \"name\": \"image-floppy-Debug-i386\",\n"
			       "                        \"type\": \"cppdbg\",\n"
			       "                        \"request\": \"launch\",\n"
			       "                        \"program\": \"${workspaceFolder}/bin/Debug-i386/os/kernel/elf/kernel.elf\",\n"
			       "                        \"args\": [],\n"
			       "                        \"miDebuggerServerAddress\": \"localhost:1234\",\n"
			       "                        \"preLaunchTask\": \"Run-image-floppy-Debug-i386\",\n"
			       "                        \"stopAtEntry\": false,\n"
			       "                        \"cwd\": \"${workspaceFolder}/os/image/floppy\",\n"
			       "                        \"environment\": [],\n"
			       "                        \"externalConsole\": false,\n"
			       "                        \"MIMode\": \"gdb\",\n"
			       "                        \"setupCommands\": [\n"
			       "                                {\n"
			       "                                        \"description\": \"Enable pretty-printing for gdb\",\n"
			       "                                        \"text\": \"-enable-pretty-printing\",\n"
			       "                                        \"ignoreFailures\": true\n"
			       "                                },\n"
			       "                                {\n"
			       "                                        \"description\": \"Set Disassembly Flavor to Intel\",\n"
			       "                                        \"text\": \"-gdb-set disassembly-flavor intel\",\n"
			       "                                        \"ignoreFailures\": true\n"
			       "                                }\n"
			       "                        ]\n"
			       "                },\n"
			       "                {\n"
			       "                        \"name\": \"image-floppy-Release-x86_64\",\n"
			       "                        \"type\": \"f5anything\",\n"
			       "                        \"request\": \"launch\",\n"
			       "                        \"preLaunchTask\": \"Run-image-floppy-Release-x86_64\",\n"
			       "                },\n"
			       "                {\n"
			       "                        \"name\": \"image-floppy-Release-i386\",\n"
			       "                        \"type\": \"f5anything\",\n"
			       "                        \"request\": \"launch\",\n"
			       "                        \"preLaunchTask\": \"Run-image-floppy-Release-i386\",\n"
			       "                }\n"
			       "        ]\n"
			       "}\n";

TEST(c_small)
{
	START;

	test_gen_file_t out[] = {
		{
			.path = "tmp/Makefile",
			.data = SLN_TEST,
		},
		{
			.path = "tmp/test/Makefile",
			.data = PROJ_C,
		},
		{
			.path = "tmp/.vscode/tasks.json",
			.data = TASKS,
		},
		{
			.path = "tmp/.vscode/launch.json",
			.data = LAUNCH,
		},
	};

	const int ret = test_gen(vc_sln_gen, NULL, c_small_in, sizeof(c_small_in), out, sizeof(out));
	EXPECT_EQ(ret, 0);

	END;
}

TEST(c_args)
{
	START;

	test_gen_file_t out[] = {
		{
			.path = "tmp/Makefile",
			.data = SLN_TEST,
		},
		{
			.path = "tmp/test/Makefile",
			.data = PROJ_C,
		},
		{
			.path = "tmp/.vscode/tasks.json",
			.data = TASKS,
		},
		{
			.path = "tmp/.vscode/launch.json",
			.data = LAUNCH_ARGS,
		},
	};

	const int ret = test_gen(vc_sln_gen, NULL, c_args_in, sizeof(c_args_in), out, sizeof(out));
	EXPECT_EQ(ret, 0);

	END;
}

TEST(cpp_small)
{
	START;

	test_gen_file_t out[] = {
		{
			.path = "tmp/Makefile",
			.data = SLN_TEST,
		},
		{
			.path = "tmp/test/Makefile",
			.data = PROJ_CPP,
		},
		{
			.path = "tmp/.vscode/tasks.json",
			.data = TASKS,
		},
		{
			.path = "tmp/.vscode/launch.json",
			.data = LAUNCH,
		},
	};

	const int ret = test_gen(vc_sln_gen, NULL, cpp_small_in, sizeof(cpp_small_in), out, sizeof(out));
	EXPECT_EQ(ret, 0);

	END;
}

TEST(os)
{
	START;

	test_gen_file_t out[] = {
		{
			.path = "tmp/Makefile",
			.data = OS_SLN,
		},
		{
			.path = "tmp/os/boot/bin/Makefile",
			.data = OS_PROJ_BOOT_BIN,
		},
		{
			.path = "tmp/toolchain/gcc/Makefile",
			.data = OS_PROJ_GCC,
		},
		{
			.path = "tmp/os/kernel/bin/Makefile",
			.data = OS_PROJ_KERNEL_BIN,
		},
		{
			.path = "tmp/os/kernel/elf/Makefile",
			.data = OS_PROJ_KERNEL_ELF,
		},
		{
			.path = "tmp/os/image/disk/Makefile",
			.data = OS_PROJ_IMAGE_DISK,
		},
		{
			.path = "tmp/os/image/floppy/Makefile",
			.data = OS_PROJ_IMAGE_FLOPPY,
		},
		{
			.path = "tmp/.vscode/tasks.json",
			.data = OS_TASKS,
		},
		{
			.path = "tmp/.vscode/launch.json",
			.data = OS_LAUNCH,
		},

	};

	const int ret = test_gen(vc_sln_gen, NULL, os_in, sizeof(os_in), out, sizeof(out));
	EXPECT_EQ(ret, 0);

	END;
}

STEST(vc)
{
	SSTART;
	RUN(c_small);
	RUN(c_args);
	RUN(cpp_small);
	RUN(os);
	SEND;
}
